### ISSUE TITLE
🥔⛰️ `Space`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1154]
`Space` organize `Client`'s data within a `Neighborhood`

## Use Cases
- [ ] 🌱 Registering a Space
  - [ ] https://github.com/zinc-collective/convene/issues/1585
- [x] https://github.com/zinc-collective/convene/issues/117
- [x] #1364
- [x] #1514
- [x] https://github.com/zinc-collective/convene/issues/74
- [x] https://github.com/zinc-collective/convene/issues/1473
- [x] https://github.com/zinc-collective/convene/issues/833
- [x] 🥔 Configuring a Space
- [x] https://github.com/zinc-collective/convene/issues/621

## Bugs
- [x] https://github.com/zinc-collective/convene/issues/1658
- [x] https://github.com/zinc-collective/convene/issues/1659

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
