### ISSUE TITLE
⛰️✨ `Sections`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1155]
- Rooms are Convene's sub-organizational unit below  https://github.com/zinc-collective/convene/issues/1154.
   https://github.com/zinc-collective/convene/issues/709 are placed in https://github.com/zinc-collective/convene/issues/1155

- From an Interaction Design perspective, https://github.com/zinc-collective/convene/issues/1155 are like a screen on a Mobile App or a landing page on a Website. Every https://github.com/zinc-collective/convene/issues/1154 has a default room, which we call the `Entrance`

## Use Cases
- [x] #1965
- [x] ✨ `Section`: Adding `Sections` to `Spaces`
- [x] ✨ `Section`: Removing `Sections` from `Spaces`
- [x] ✨ `Section`: Limit `Sections` to `Spaces`

## Data Model
- [x] #1961
- [x] #2228

## Design

- [ ] #1472

## Bugs

- [x] https://github.com/zinc-collective/convene/issues/1841

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
