### ISSUE TITLE
Furniture: Videobridge - Joining Room at Capacity

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#119]
Because our Videobridge cluster has limited capacity, we need to be careful about allowing too many people into video rooms at the same time. 

Each Space has a Capacity, which indicates how many people can be in it at a time. 

Note: We are considering allowing people to buy “Passports” which allow them to access a Space  at Capacity but I think that’s a different feature.

## TODO
- [ ] Testing:
  - [ ] Migrate Scenario into the `features/furniture/jitsi-videobridge.feature`
  - [ ] Wire in the steps definition
- [ ] Design 
  - [ ] Wireframe what a Waiting Room looks like
  - [ ] Do we keep a queue or something so that as people are waiting they are let in? Or do we just hope people refresh for now?
 - [ ] Engineering
   - [ ] How do we want to store the Capacity for a particular Jitsi Videobridge cluster? 
   - [ ] How do we keep track of the current usage vs the maximum capacity?
   - [ ] How do we update the current usage on join and part?

## Feature Definition
```features/furniture/jitsi-videobridges.feature
  
  Scenario: Cannot Connect When at Capacity
    Given a Space with a Jitsi Videobridge with a Capacity of 2
    And 2 Guests are Active in a Room with a Jitsi Videobridge
    When another Guest attempts to enter the Room with a Jitsi Videobridge
    Then the Guest is told they may not connect until someone else leaves the Videobridge
    
```
