### ISSUE TITLE
Guest must know the Room Key before entering a Locked Room

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#12]
Part of https://github.com/zinc-collective/convene/issues/40
```
Scenario: Guest who knows Room Key can access Locked Room
  Given a Workspace with a Locked Room
  When a Guest enters the correct Room Key
  Then the Guest is placed in the Room
  
Scenario: Guest who does not know Room Key cannot access Locked Room
  Given a Workspace with a Locked Room
  When a Guest enters the wrong Room Key
  Then the Guest is not placed in the Room
```

### This Issue May Be Closed When
- [ ] Guests must provide a Room Key before entering a Locked Room
- [ ] ~We have written a Guide for Clients for setting and changing a Rooms Key~ This seems like it should be in a different part of #40 

### TODO:
- [x] Place feature tests in the code base (https://github.com/zinc-collective/convene/pull/54)
- [ ] Wire in the feature tests
- [ ] Design UI for entering a room key before opening a room 
- [ ] Implement UI for entering a room key before we open a room
- [ ] Generate JWT tokens in `convene-web` 
- [ ] Require JWT tokens to access a room in JITSI

## Notes

Droppin in links to read later:

### If we want to explore using Jitsi's token system as a seam
- https://github.com/jitsi/jitsi-meet/wiki/LDAP-Authentication
- https://github.com/jitsi/jicofo#secure-domain
- https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md (search for jwt)
- https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

### If we want to use NGINX as a seam
- https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
- https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/
- https://stackoverflow.com/questions/26223733/how-to-make-nginx-redirect-based-on-the-value-of-a-header
- http://nginx.org/en/docs/http/ngx_http_map_module.html#map

**Comment by zspencer** [comment]
From @colombene
> How do you define “workspace”? Is it a specific session or the general launch webpage
At present, I'm defining a "Workspace" as the full subdomain a Convene deployment lives behind, such as convene.example.com.

Also from @colombene 
> Would anyone who attends any meeting from a workspace be able to access any other meeting or create their own meeting with the secret? If so, I don’t think it would be adequately secure.

I think we could do some reframing and filling in for the Private rooms scenarios to decide which we want to apply as part of the 1.0 Milestone. For example, which of these (and any missing ones) must be applied before we release 1.0?

- Visitor provides Workspace's Secret Code to enter the Workspace
- Visitor provides Workspace's Secret Code to enter a Room
- Visitor provides Room Secret Code to enter a Room
- Visitor Provides Personal Secret Code to enter a Room
- Visitor Provides Personal Secret Code to enter a Workspace

**Comment by zspencer** [comment]
This issue seems to be well encapsulated by #40, so I’m closing it out.
