### ISSUE TITLE
🥔✨ `Marketplace`: Buying 🥡 `Products`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1326]
-  https://github.com/zinc-collective/convene/issues/831

## Use Cases

- When https://github.com/zinc-collective/convene/issues/1326 a #2043 moves through four stages:
  1. Beginning their #2215 including finding a  #2044 and setting their https://github.com/zinc-collective/convene/issues/1136
  2. Assembling their #2215 by browsing the #2153 and adds  #2169(s) to their https://github.com/zinc-collective/convene/issues/2155. 
  3. Checking Out, which consists of reviewing their #2155, confirming their https://github.com/zinc-collective/convene/issues/1136 and https://github.com/zinc-collective/convene/issues/1763, and making a Payment to finalize their #2215
  4. Picking up or Receiving the https://github.com/zinc-collective/convene/issues/1325 for their   #2215

- [x] 🥔 Preparing to Buy 
  - [ ] #2378
  - [x] #2153
  - [ ] #2155
  - [x] 🥔 Adding `Product`s to `Cart`
  - [x] 🥔 Adjusting `Product` quantities in `Cart`
  - [x] 🥔 Removing `Product`s from `Cart`
  - [x] 🥔 Setting `Delivery` details
- [x] 🥔 `Marketplace`:  🕺`Shopper` Checks Out 🛒`Cart`
  - [x] https://github.com/zinc-collective/convene/issues/1672
- [x] 🥔 Paying for `Order`
  - [x] 🥔 Pay using Credit or Debit Card via Stripe 
  - [x] 🥔 Buyer receives Order Placed email with permalink to `Order`
  - [x] https://github.com/zinc-collective/convene/issues/1238
  - [ ] Pay using Cash.app https://github.com/zinc-collective/convene/issues/832
  - [ ] Pay using Venmo https://github.com/zinc-collective/convene/issues/832
  - [ ] Pay using Zelle https://github.com/zinc-collective/convene/issues/832
  
## Domain Model
  - https://github.com/zinc-collective/convene/issues/2169
  - https://github.com/zinc-collective/convene/issues/2153
  - https://github.com/zinc-collective/convene/issues/2155
  - https://github.com/zinc-collective/convene/issues/2215
  
## Bugs
  - [x] https://github.com/zinc-collective/convene/issues/1657
  - [x] https://github.com/zinc-collective/convene/issues/1983
  - [x] https://github.com/zinc-collective/convene/issues/2002
  - [x] https://github.com/zinc-collective/convene/issues/1962
  - [x] https://github.com/zinc-collective/convene/issues/2198
