### ISSUE TITLE
🌫️ `Neighborhood`: Trust and Safety

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#1450]
- https://github.com/zinc-collective/convene/issues/892 
- https://github.com/zinc-collective/convene/issues/103

One of Convene's key goals is to:
  - Build high-trust relationships between `Neighbors` and `Visitors` and 
  - Protect `Neighbor`s from malicious Domains and Actors
  
We intend to take a pretty heavy-handed approach initially, building upon the wisdom and prior art of folks like:
- [@Are0h](https://ubiqueros.com/@Are0h)
- [@CaribenxMarciax](https://scholar.social/@CaribenxMarciaX)
- [@gingerrroot](https://kitty.town/@gingerrroot)

## Use Cases
- [ ] Registration Protection
  - [ ] `Operators` may prevent registrations from particular domains
  - [ ] `Operators` may allow registrations from only particular domains
- [ ] `Neighbor` Moderation
  - [ ] `Operator`s may block a `Person` from any `#create` or `#update` actions.
  - [ ] ???
- ???

## A Brief History of Trust and Safety 
Web 1.0 improved data security, bot-mitigation and spam prevention through SSL, sender filtering, etc. Services like [Barracuda](https://www.barracuda.com/) and (Akamai](https://www.akamai.com/) led the charge at the network level, while SSL became the standard for secure Client <=> Server communications.

Web 2.0 further reduced malicious, brutal, or disturbing content through active moderation and automated flagging, and even some community-based collective blocking such as [BlockTogether](https://blocktogether.org/). [LetsEncrypt](https://letsencrypt.org/) made SSL available without cost to every site that wanted it.  [Fastly](https://www.fastly.com/products/web-application-api-protection) and [Cloudflare](https://www.cloudflare.com/application-services/solutions/) popularized low-cost, drop-in Web Application Firewalls. Facebook, Google, etc. began investing in manual and automated content auditing and moderation (with varying degrees of success and bias).

The Fediverse ("Web 3.0") has `#FediBlock` and [similar projects](https://codeberg.org/nev/awesome-fediadmin#user-content-moderation-blocking) and began to normalize personal authentication keys in the form of "Wallets".

**Comment by zspencer** [comment]
Some random gibberish thoughts for later

- What if we leverage / license [thebad.space](https://thebad.space) to populate shady-domains
- What if we had different "levels" or "kinds" of trust? I.e. a High-Trust Federated `Neighborhood` or `Space` could have different federation behaviors than a low-trust, unknown, suspicious, or malicious `Neighborhood` or `Space`
- ???

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424)
