### ISSUE TITLE
Furniture: Breakouts

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#154]
### TODO
- [ ] Write a feature definition
- [ ] Spike an implementation (with or without "furniture" concept)
- [ ] Spike how to have events like `workspace.room.breakout-rooms.created` and `workspace.room.breakout-rooms.expiring-soon` etc. distributed to each room occupant.
- [ ] Migrate the feature definition to the code-base
- [ ] Creating Breakout Rooms
  - [ ] Sketch Feature Definition
  - [ ] Make a UI Mockup
  - [ ] Wire in step definitions
  - [ ] Implement it!
- [ ] Entering Breakout Rooms
  - [ ] Sketch Feature Definition
  - [ ] Make a UI Mockup
  - [ ] Wire in step definitions
  - [ ] Implement it!
- [ ] Enable feature globally!

```feature/breakout-rooms.feature
Feature: Breakout Rooms
  In order for people to organize themselves by topic
  Members want to be able to create named breakout rooms within a room
  And Guests want to move between those rooms leisurely

Scenario: Creating Breakout Rooms
  Given a Room with Breakout Rooms enabled
   When a Member adds the following Breakout Rooms
    | name                           | expires        | access   | 
    | Business Model Canvas Workshop | in 1 hour.     | public.  | 
    | Engineering.                   | in 3 hours     | internal | 
    | Standup.                       | in 15 minutes. | public.  | 
   Then the "Engineering" Breakout Room is visible to:
    | Members | 
    | Owners  | 
    And the "Engineering" Breakout Room is visible to:
    | Guests | 
   Then the "Standup" Breakout Room is visible to:
    | Members | 
    | Owners  | 
    | Guests  | 
   Then the "Business Model Canvas" Breakout Room is visible to:
    | Members | 
    | Owners  | 
    | Guests  | 

Scenario: Entering Breakout Rooms

Scenario: Breakout Room Expiration
```
