### ISSUE TITLE
Navigate Between Convene and Other Browser Tabs

### ISSUE THREAD

**Issue by hangtwenty** [zinc-collective/convene#160]
## Original Motivation (by @hangtwenty)
> Subject: The page <title> doesn't have "Convene" in it
>
> The page <title> doesn't have "Convene" in it, so it was hard for me to switch-tab to it just now. (oh tabs)

## TODO
- [x] Define the intent behind the feature.
- [ ] Move the feature definition to the repository (https://github.com/zinc-collective/convene/issues/160)
- [ ] Implement Steps (Note: I don't know if this is possible with webdriver; so we may strike-this out at some point)
- [ ] Implement Feature 
   - [ ] Add a Favicon: [W3C Guidance](https://www.w3.org/2005/10/howto-favicon), [Cheat Sheet](https://github.com/audreyfeldroy/favicon-cheat-sheet)
   - [ ] Include the Brand Name, Space name and (when possible) Room name in the Title tag (https://github.com/zinc-collective/convene/issues/160)

## Design Notes
- Some browsers "bundle" tabs into just their favicon; which means that folks who have lots of tabs open will have a hard time picking Convene out if this is purely a textual change
- It's also not entirely clear to me how wide of text will show up on different browsers; but I _think_ it's "left-to-right" in languages that are read left-to-right; so we want to order the title as Room Name -> Space Name -> Brand name

**Comment by hangtwenty** [comment]
I'll do a quick change

**Comment by zspencer** [comment]
This is a great point! I've issued you [20 patronage points](https://airtable.com/tblndyi9VR3shxtmS/viwxgldsOPhzLxfpV/recxcU0CXO07kzj1S) for raising it to our attention! 

I'm going to do some editing of the top-level issue to reframe it around the problem-to-solve; and add some bullet-points for the things to think through or actions to take in order to resolve it!

**Comment by zspencer** [comment]
Aight, I've updated it! Please keep in mind that we don't expect people to do _all the things_. Starting with just the text makes a ton of sense; but feel free to take a stab at making one if you want! Or check with @colombene if we have a logo that's suitable for rendering as a favicon.

**Comment by zspencer** [comment]
I'm going to close this for now, especially as we need to think more about how Branding works across custom domains; etc.
