### ISSUE TITLE
Profiles:  Creating a Profile

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#165]
Builds on: 
- [ ]  See: https://github.com/zinc-collective/convene/issues/153

Prompted by: https://github.com/zinc-collective/convene/pull/163/files#diff-a18db26ce84b0f09946b94368f78b894c79085e071a26c92f80d41df0ca14fd4R17

Wireframes: 
- For configuring Identity Presentation: https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/a8ab794e-bd5b-467b-b02a-2fedaac620e6/
- See the top-right nav for where the Identity Presentation is shown: https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/69c4a16b-baab-4ba3-b42f-ee2073aa0adc/

Note: It's likely that the wireframes for configuring the Identity as a registered space member may be distinct from the wireframes for configuring the name/pronouns/location when entering a Room; however I think it's the closest bit we have at present.

## TODO
- [ ] Space Member Configures Identity Presentation
  - [ ] Feature definition is written
  - [ ] Step definitions are implemented
  - [ ] Coded
  - [ ] Documented
  - [ ] Release notes written

## Feature Definition
```features/identity-configuration-and-presentation.feature
Feature: Identity Configuration and Presentation
  In order to build connection with other folks in Convene Spaces
  I want to project an Identity that feels like a safe representation of myself

Scenario: Space Member Configures Identity Presentation
  When a Member configures the following aspects of their identity:
    | aspect    | value              | 
    | name      | jay                | 
    | pronouns  | they/them          | 
    | location  | Oakland, CA        | 
    | 2d_avatar | falling-polar-bear | 
   Then the Member's identity is presented in the nav header when they are logged in
# See: https://github.com/zinc-collective/convene/issues/153
    And the Space Member's identity is visible to other Room occupants when in a Room
```

Notes:
![falling-polar-bear](https://www.pl-law.com/wp-content/uploads/2015/05/polar-bear-ice-fall-over2-960x540.jpg)

**Comment by zspencer** [comment]
@colombene - You've sprinkled some iconography that I think implies an avatar for folks throughout the wireframes; so I wanted to make setting that an explicit feature that can be shuffled around / worked on by folks.

My instincts are this goes into the "B" milestone, unless someone is particularly enthusiastic about it and/or we blow through the A milestone issues.
