### ISSUE TITLE
Rename `Workspace` to `Space`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#184]
As we move away from Convene as only for work, I'd like us to do a bit of cleanup on the naming in our application to more closely mirror the trajectory we're headed.

# TODO
- [x] Tests are updated to use Space instead of Workspace
- [x] Documentation is updated to mention Space instead of Workspace
- [x] Backend Code: Rename the `Workspace` model to `Space`
- [x] Backend Code: Have the `/workspaces/*` paths redirect to `/spaces/...` using `moved permanently`...
  - [ ] Encourage folks to update their bookmarks? 
     - [ ] Maybe add a "flash message" to update their bookmark?
     - [ ] Maybe instead of a redirect, have a 404 that suggests they go to the next place?
  - [ ] Log redirects from workspaces to space so we can get an idea for how many folks are still hitting the dead link (Perhaps using [Ahoy](https://github.com/ankane/ahoy)?)
    - [ ] Install Ahoy (if it's not installed already) and configure it to track the redirects
    - [ ] Install Blazer (if it's not installed already) and create a dashboard that tells us what's up

#### Later? Or sooner?
- [ ] Remove the Redirect completely and leave a 404 (ideally that signposts to the new name)
  - [ ] Design a useful + adorable 404 page
  - [ ] Code the 404 page into the project

**Comment by anaulin** [comment]
If we change the defaults sooner rather than later, it is unlikely that folks outside of Zinc would have any bookmarks to the `workspace` version of the URLs, which would let us skip the "encourage folks to update bookmarks" bits, maybe?

**Comment by zspencer** [comment]
yea, I think I over-did it in my planning :). I've got the major bits taken care of here: https://github.com/zinc-collective/convene/pull/188

**Comment by zspencer** [comment]
This is done enough for now. Closing it out.
