### ISSUE TITLE
`Gizmo`: Payment Form

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#186]
Motivated by potential customer / interested party who have the following need:
1. Have the Investors log in to their bank account using Plaid's Auth Service.
2. Use that to pull their checking/savings details.
3. Ideally, pull that data out as a NACHA file from Plaid, so that they can then upload manually into a banking provider for ACH.

### TODO

- [x] Write Feature Definition (with supplementary links and such)
- [x] Shift the current VideoBridge to a piece of furniture in all Rooms (So we can have Rooms without a Video Bridge) (https://github.com/zinc-collective/convene/pull/191)
- [x] Make Plaid Utility
  - [x] ~Add an API Version drop-down to the Plaid Utility Configuration~ This is tied to gem version; so we can't reall swap between them.
  - [x] Add Validations to the Plaid  Utility Configuration
- [x] Spike using Plaid Link to Connect an Account and Auth to retrieve Account Numbers
  - Auth Docs: https://plaid.com/docs/api/products/#auth
  - Link Docs: https://plaid.com/docs/link/
  - https://fin.plaid.com/articles/inside-ach-payments-with-stripe-and-plaid/
  - How Do?
    - [x] Make a Form and Active Record object that stores a "Check" (Name of Payee, Date, Amount, eSignature, Plaid Account Link ID)
    - [x] Set up Link to get the Plaid Account ID
    - [x] Set up Auth to retrieve the Account Number and Routing Number
    - [x] Expose all the check(s) to Space Members
    - [x] ~~Expose just the check(s) the person deposited to non Space Members~~
- [ ] Payment Form shouldn't explode the Space when Plaid isn't setup.
- [ ] Allow a `FurniturePlacement` to have many `:utility_hookups` so the `FurniturePlacement` knows which utilities to use.
- [ ] Spike building a NACHA file (Perhaps using [the ach gem?](https://github.com/jm81/ach)
  - Some docs on NACHA: https://www.mercbank.com/pdfs/Standard%20NACHA%20ACH%20File%20Format.pdf

- [x] Is Stripe A no-go? https://stripe.com/restricted-businesses

Notes from audit 12/15/2021
   - [x] add validations to form
   - [x] reframe to "payment" and away from "check" terminology
   - [ ] add some kind of help text that clarifies that this is a payment authorization, and the payment won't happen immediately
   - [ ] add input mask for "Amount" field, so that it looks like dollars
   - [ ] color on hover on the "Create" button looks weird
   - [ ] add checkbox for payer to mark "I authorize this charge" (check with EBPREC for specific authorization wording) 
   - [ ] add "entryway" for payments -- the room should show a button for "make a payment", which then takes you to the payment form
   - [ ] improve UI for "see all checks" (link at bottom of form), maybe:
     - [ ] in "entry to payments" element (see above), add button to "see payment history"; should look "admin-y", to make it clear that regular users have no access to this (maybe this "entry" element has an "admin" section) 
   - [ ] confirmation text "Your payment for XXX was successfully created" should show amount as a money amount ($XXX)
   - [ ] on creation, we should send an email confirmation that includes 4 last digits of account, amount, and routing number
     - [ ]  ideally, also a way to link back to see the status and/or to cancel the payment
     - [ ] later on: audit the payer ("accounts receivable") side of things, which needs a way to update "status", better UI, etc 

```features/furniture/check-drop-box.feature

Feature: Furniture - Check Drop Box
  In order to reduce transaction fees when accepting large payments
  As a Space Owner
  I would like to accept Electronic Checks


  # At present, we're exploring using [Plaid Link] and [Plaid Auth] as the
  # mechanism for collecting and verifying ACH details. They have provided
  # a particularly nice [Modern Guide to ACH].
  #
  # Because we do not store any financial account data, we should be compliant
  # with [PCI DSS].
  #
  # There are two primary use-cases here:
  #
  # 1. Dropping off a check for (eventual) deposit
  # 2. Providing the checks to the Space Owner
  #
  # At present, we are _not_ automating the ACH transfer, though there are many
  # [Payment Processor integrations for Plaid]. Instead, we are opting to
  # expose a [NACHA file], which can be uploaded to many financial institutions
  # business portals.
  #
  # [Plaid Link]: https://plaid.com/docs/link/
  # [Plaid Auth]: https://plaid.com/docs/auth/
  # [Plaid Auth API Docs]: https://plaid.com/docs/api/products/#auth
  # [Payment Processor integrations for Plaid]: https://plaid.com/docs/auth/#using-a-payment-processor
  # [Modern Guide to ACH]: https://go.plaid.com/rs/495-WRE-561/images/Plaid-Modern-guide-to-ACH.pdf
  # [PCI DSS]: https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard
  # [NACHA file: https://files.nc.gov/ncosc/documents/eCommerce/bank_of_america_nacha_file_specs.pdf
  Background:
    Given a Space with a Room with Check Drop Off Furniture fully configured

  # For valid link credentials data, see https://plaid.com/docs/auth/coverage/testing/#testing-the-link-flow
  Scenario: Dropping off an Electronic Check with a Valid Bank Account
    Given a Guest begins the Check Deposit Workflow with the following data:
      | check_amount          | $1000                     |
      | earliest_deposit_date | 1 week from now           |
      | memo                  | Initial investment amount |
      | email                 | person@example.com        |
      | name                  | Person McMoney            |
      | signature             | Person McMoney            |
    When a Guest completes the Plaid Link Workflow with valid credentials
    Then the Space Owner's Pending Check's list includes the Check
    And the Space Owner's Pending Checks NACHA file looks like:
      """
      lol i don't know i need to look the file format up
      """
    And the Guest receives an Email letting them know that their Check is Pending Deposit

  Scenario: Depositing Pending Checks from the Check Drop Box
    Given there are Pending Checks in the Check Drop Box
    When a Space Owner downloads the Pending Checks
    Then the downloaded NACHA file file looks like
      """
      lol i don't know this yet either
      """
    And the Check Drop Box has no Pending Checks
    And the Check Drop Box has the formerly pending checks Deposited
    And the Depositors receive an email letting them know their Check is being deposited.
```

**Comment by anaulin** [comment]
@zspencer placeholder for any notes we want to make for this prototype. Didn't add it to any milestone, since I don't know what might make sense. Please edit / rearrange as appropriate.

**Comment by zspencer** [comment]
Thanks @anaulin !!!

**Comment by colombene** [comment]
Can someone provide more context on this? Like... what is happening between who in this scenario? Who is the potential customer or what is their business/activity? Who are their investors? What other kind of interaction/communication is happening at the point of this event? What does Plaid do? What is NACHA and ACH or what is being transferred?

**Comment by zspencer** [comment]
I've updated the body with a "Line of Action" for how the scenarios may play out. My plan is once #191 is merged and safely deployed to begin putting together a branch to begin playing with Plaid Link.

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
