### ISSUE TITLE
Operator Provisions an Always On Virtual Office Space on AWS

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#2]
```features/video-workspaces.feature
Feature: Video Workspaces
  In order discuss things face-to-face within my organization
  As Colin Collaborator and Felicia Faciliator
  I want a Video Workspace

  @0.1-alpha
  Scenario: Operator Provisions an 8 person Video Workspace on AWS
    Given an Operator has ran `jitsi/build` for {{clientDomain}}
    When an Operator runs the `jitsi/provision` command with:
      | arguments                        |
      | --client-domain={{clientDomain}} |
    Then a JITSI meet instance is available at https://{{clientDomain}}

  @0.1-alpha
  Scenario: Operator Builds an 8 person Video Workspace on AWS
    When an Operator runs the `jitsi/build` command with:
      | arguments                        |
      | --region=us-west-1               |
      | --provider=aws                   |
      | --client-domain={{clientDomain}} |
    Then a convene-jitsi-{{clientDomain}} is available within the us-west-1 region
```

Deploy Instance: 
- [x] Automate launch an instance
- [x] Automate apply a ssl certificate
- [x] Automate configure network setting ( Look into Terraform )

Release Instance:
- [x] Automate point DNS record to the instance

Install Jitsi
- [x] Automate interact with Jitsi interface

**Comment by maximegalon5** [comment]
Who is the Operator? Does the Operator have a _technical_ background? If so, then this looks straightforward to me. I'm guessing the intention is to translate arguments into UI equivalents making it easier for non-technical Operators too?

**Comment by user512** [comment]
@zspencer Do you know if we have a ssl certificate to test with?

**Comment by zspencer** [comment]
You will probably want to self-sign a certificate for testing purposes (unless that doesn't work, in which case we should buy a wildcard *.zinc.coop cert.

**Comment by zspencer** [comment]
@user512  - Would you be willing to go through feature test end-to-end by hand and confirm that you're able to spin up a brand new convene installation without any trouble? And if you _do_ experience trouble, could you add some check-boxes for us to pick off over the next week or two?

**Comment by maximegalon5** [comment]
@zspencer I'm reading this issue as Vivek can go to meet.zinc.coop and create Vivek's Music room and then share that link. If this is the correct interpretation, what action do you need from me to _accept_ /_confirm_ this?

**Comment by zspencer** [comment]
@maximegalon5 - This issue _probably_ needs to be confirmed by @user512  or @cjoulain as they are more familiar with infrastructure management and terraform. If you _want_ to become that person, I won't stop you, but it would require getting set up as a "developer/site reliability engineer" on the project, with a local environment that can manage our infrastructure, which is something @user512 already has.

Sorry :(.

**Comment by maximegalon5** [comment]
@zspencer I agree. I'll wait for @user512 or @cjoulain to confirm and then close the task.

**Comment by user512** [comment]
@zspencer, I still feel confused on how to get it running, scheduled a session with you.

**Comment by zspencer** [comment]
@user512 - Great! I also updated the feature definition in the issue to match the feature definition that we wound up building. Essentially, confirmation for this is:

1. Can you spin up a Convene instance for your own domain by following the steps defined in the features?
2. If not, what do we need to change or document?

**Comment by zspencer** [comment]
@user512 and I paired on creating a `convene-test.zinc.coop` client to demonstrate provisioning a new client; and it went well! I think we're going to see a few more rough edges as we add clients; but this feels "good enough" for now.
