### ISSUE TITLE
Spaces: Customization

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#23]
```features/branded-spaces.feature
Feature: Branded Spaces
  In order to have a place that is truly mine
  As a Space Owner
  I want to be able to brand my space with communicative and cosmetic details
```

### TODO
- [ ] Design
  - [ ] Write User Journey for Branded Spaces
  - [ ] Mockups for where to Configure Branded Spaces
- [ ] Space Names
  - [ ] Space Owner may set their Space Name
- [ ] https://github.com/zinc-collective/convene/issues/74
- [ ] Themes

### Done
- [x] Remove Jitsi branding
  -  Google Slides laying out where in the UI these exist https://docs.google.com/presentation/d/15KlJoJRFng3xadSw1o0E0xSunGWpECSEcdBRiZBgDBA/edit#slide=id.g860bdd4a39_0_3
  - Logo: https://drive.google.com/drive/folders/1Rmj17dQweGt5l9EFFBrp_9DHIY1WHmG2 
  - [x] In Rooms
    - [x] People are called "Participants" instead of "Fellow Jitsers"
    - [x] The  `jitsi.org` + logo watermark is removed
     - [x] ~~And replaced with the [Convene Logo](https://drive.google.com/drive/folders/1Rmj17dQweGt5l9EFFBrp_9DHIY1WHmG2)~~
    - [x] The `Jitsi` name is replaced with `Convene` when requesting permissions for video and audio
      - [x] in the Browser prompt (This is correct on convene.zinc.coop, but not on meet.zinc.coop)
      - [x] In the web page "Jitsi Meet Needs to..."
  - [x] ~~When Links are "unfurled" into Facebook/Slack/Etc it says "Convene" and not "Jitsi"~~

**Comment by maximegalon5** [comment]
I've created a [G Slide](https://docs.google.com/presentation/d/15KlJoJRFng3xadSw1o0E0xSunGWpECSEcdBRiZBgDBA/edit?usp=sharing) where I've pointed to some considerations.

They revolve around:

- replacing with the Convene Logo <- which means we have to decide and pick something

- Consider changing the "meet.zinc.coop" URL if we believe the branding is inconsistent with Convene (would love to know what @colombene @cricketlova think about this).

- Consider changing the text on the landing page. I've made suggested changes in the Notes section of the slides, but defer to @colombene for a final go ahead.

**Comment by cricketlova** [comment]
@maximegalon5 - I am very pro- removing jitsi branding in place of Convene's. The two experiences feel completely different right now and have no reason for a customer to believe that they're the same.

Additional thoughts:
- changing color palette to match what has been made on (https://www.zinc.coop/convene/)
- changing the favicon

**Comment by cricketlova** [comment]
& out of the two logos, definitely prefer 'C' one over the weird one. Is there a vector file for the 'c' logo? I'd love to dabble around with them a bit (no promises that it will be any better)

**Comment by maximegalon5** [comment]
@cricketlova we didn't but I used Inkscape to create one [here](https://drive.google.com/open?id=1Rmj17dQweGt5l9EFFBrp_9DHIY1WHmG2). Let me know if that works or if there is any other ones you need me to convert. 

The C one seems to be preferred by us all atm.

**Comment by zspencer** [comment]
@cricketlova and @maximegalon5 - I've created a set of checkboxes for each of the items to take care of during branding. We are choosing _not_ to change the `meet.zinc.coop` landing page at this time; because we expect that to be a place where we'll want to do more heavy construction before we release Andromeda.

@cricketlova  - Could you give me more specifics on what in the "in room" experience you think we should replace with which colors? Ideally with hex-codes?

**Comment by user512** [comment]
Moving this back to in-progress because we haven't rebrand `Jitsi Meet needs to use your microphone and camera.`

My understanding is we simply need to passed `interfaceConfig.APP_NAME` to override this but we have already done that and it doesn't wokr.
Below is the source code referencing the user media permission overlay.
https://github.com/jitsi/jitsi-meet/blob/8e9a51f74297f26d569283f02afb6fc2674677ff/react/features/overlay/components/web/UserMediaPermissionsOverlay.js#L36
https://github.com/jitsi/jitsi-meet/blob/8e9a51f74297f26d569283f02afb6fc2674677ff/lang/main.json#L661

**Comment by user512** [comment]
Found this, looks like the Jitsi team disabled that, so we will have to edit the js code in Jitsi Meet to achieve that. https://community.jitsi.org/t/app-name-doesnt-have-effect/71648/2

**Comment by zspencer** [comment]
@maximegalon5 - In your usage over the past week have you seen `JITSI` branding anywhere?

**Comment by maximegalon5** [comment]
> @maximegalon5 - In your usage over the past week have you seen `JITSI` branding anywhere?

No, I have not. Went to the demo site and fiddled around with it and don't see `Jitsi` anywhere, currently.

**Comment by maximegalon5** [comment]
![Annotation 2020-08-24 113752](https://user-images.githubusercontent.com/7209665/91083067-84c24700-e5fe-11ea-9a4d-435e040436e4.png)

Also here.

**Comment by user512** [comment]
Still showing Jitsi Meet, I can take a look again.

**Comment by user512** [comment]
Provisioned a new video bridge instance with a new snapshot that has the brand name changes. 
Ready to be confirmed.

**Comment by zspencer** [comment]
Thank you! This looks like it's working! I must have screwed up something when I allocated an instance...

**Comment by user512** [comment]
Likely because I delete the wrong snapshot after testing https://github.com/zinc-collective/convene/pull/84.

**Comment by zspencer** [comment]
I'm expanding this issue to include more things around expression of color, as well as the domain-level customization
