### ISSUE TITLE
🥡 `Marketplace::MenuGroup`

### ISSUE THREAD

**Issue by rosschapman** [zinc-collective/convene#2340]
### Use Cases

- [x] Setting `Marketplace::Product`'s `Marketplace::MenuGroup`
- [ ] https://github.com/zinc-collective/convene/issues/2378

### Execution Plan

April has pointed out - rightly so - that Product "menus" on Convene look "haphazard" because we don't allow sorting or categorization. Fortunately, @zspencer's implementation of #2189 laid a strong foundation for improving organization of product pages. 

**✅ DECISION:** As a first step, let's implement the capability for Marketplace administrators to group Products under  _sections_ (err...menus, aisles, taxonomy pending...). 

During spirited text-based Discord task planning, there was first some temptation to consider a separate model for _Product Section_ with a _many_ association to tags. This way Marketplace admins could manage these sections via a typical CRUD-y workflow, similar to managing other entities like Tags, Tax Rates, or Products. However, @anaulin encouraged us to consider enhancing `Tags` themselves without introducing any new entity relationships. Because tags and taxonomies are user-generated the use cases across customers will inherently evolve to be nuanced, various, and non-linear. In other words, hard to predict from our vantage point.  Ultimately we hoist a strong risk if we design a rigid relationship structure into the data model from the start.

**✅ DECISION:** After some deliberation, @anaulin proposed a (most reasonable) minimum set of requirements we need to deliver to support grouping of tags in sections on the page. Let's do these, show them to April, and start the feedback loop quickly.

**Phase 1**
- [x] A person can mark a tag as a "section"
- [x] We can retrieve a list of products that belong to a "section"
- [x] We can retrieve a list of all the "section" tags

**Phase 2**
- [x] A person can (re)order sections by drag and drop

**Further development tasks/considerations:** 
- [ ] `Tag` will be extended with a `boolean` field like `is_section`
	- [ ] Show a checkbox in the Add/Edit Tag UIs
- [ ] Tags should be sortable (we use `ranked-model`)
- [ ] Default section sort is by alpha
- [ ] 

**🔮 Considerations for the future:** 
- Adding the concept of a `TagGroup` or `TagCollection` would be necessary if we have a reason to display all the tags for a single  group, or inversely all the groups of a single tag. 
	- This could be a achieve with polymorphism (`TagGroupable`) although it won't be necessary if we only have a Tas and TagGroups
	- In this data model there's the possibility of needing to restrict certain tags (or all?) to be belong to one group

# April's ask from email thread with Zinc & Co11ectiva

> **Back end function ask**: Currently the menu order for Oakalandia looks haphazard. 
> I'd like to be able to drag and reorder based on categories like Beverage, Lunch, Breakfast
> 
> A few catering menu items for Oaklandia have options for add ons ( see attached example) 
> A few catering menu items are priced as a range. In cases we entered the higher amount but need to ask Oaklandia about that or > include verbiage to clarify

**Comment by zspencer** [comment]
I can expect she will want to be able to order these (i.e. breakfast, lunch, then dinner) as well; but grouping is a good first step!

**Comment by rosschapman** [comment]
@zspencer Right. I'll add that as a part of a "Phase 2" in the description.

**Comment by rosschapman** [comment]
🤝 I'm closing this ticket to tie a bow on the implementation of a menus prototype. April has not expressed further interest in this feature recently.
