### ISSUE TITLE
Marketplace Menus: 🪩🥂🍾✨ and next steps

### ISSUE THREAD

**Issue by rosschapman** [zinc-collective/convene#2426]
## 🚀😀🥳👌🏽  Menus are a thing now!
Last week we released the first iteration of improving the ordering experience on the Marketplaces. This effort was initially kicked off with a request from our client Piikup for more control over how Marketplace Products were displayed, including product order and gouping: https://github.com/zinc-collective/convene/issues/2340. Effectively this meant allowing configuration of *menus* -- a common behavior of retail web applications. 

Here's all the bodacious, beautiful code from this initial release:

1. https://github.com/zinc-collective/convene/pull/2390
2. https://github.com/zinc-collective/convene/pull/2391
3. https://github.com/zinc-collective/convene/pull/2408
4. https://github.com/zinc-collective/convene/pull/2361

## ✨🤩🌿 Menus twisted our arm to refactor
Beyond enabling better segregation of products into menu "sections" (eh, terminology WIP) (ie sub-menus, or topical groupings), this work provided additional utility as a vessel for interrogations of our domain model and marketplace management UI. Like, the relationship of Tags to a Bazaar, and how tag and menu management can be more humanistic and less an expression of the datastore.

## ✨🌸🐞🛍️🥡 Coming up
There's more work to do. Here's a sketch of what's obviously missing and what questions still need answering.

### 🤗👉 Tasks ready to go 
- [x] ✨ Marketplace admins should be able to _delete_ tags (Done: https://github.com/zinc-collective/convene/pull/2431)
- [x] 🌸 _Menu tags_ are redundantly displayed on the product. See how the the `featured` tags is shown on the Banana product when already under the Featured section. (Done: https://github.com/zinc-collective/convene/pull/2431)
	![image](https://github.com/zinc-collective/convene/assets/5185/17da052a-5b5d-4a27-a5ba-61fe5164b010)
- [x] ✨ Let's add a sensible default sort order for products. Alphabetical should suffice. (Done: https://github.com/zinc-collective/convene/pull/2431)
- [x] 🌸 Consistent tag design. Right now tags are displayed as plain text and/or pills across admin and end-consumer interfaces. Should probably institute a common "pill" design (Done: https://github.com/zinc-collective/convene/pull/2431)

### 💭🤔🤨🧐🧠 Tasks that need more thought/design

- ❓Better interfaces for managing tags and menus, and possible better integration with Product admin
	- Clarify the distinct interfaces for managing menus and tags
		- Eg: right now you mark tags as a menu tag after creation. 
		- But there should probably one-step user action for creating a menu tag. 
		- It's not clear how to add a menu. Can you guess from this page?
		![image](https://github.com/zinc-collective/convene/assets/5185/465294f9-8402-48c5-aa3b-b1483a778f96)
	- Calls to action are hidden
		- Eg: Right now existing tags are just hyperlinked to an edit screen, so it's not easily discoverable what actions you can take on a tag from the main Product Tags page
	- There's no clear workflow from adding tags to adding them to products. As hinted in this section heading, it's worth exploring better integration of product and tag management in a single interface. 
	- Enriched tag data
		1. Possible: count of products assigned with tag (Done: https://github.com/zinc-collective/convene/pull/2431)
		2. At a glance the user should gain a better understanding of their marketplace menus and products
- ❓ The domain language is a mess at the code and interface level. We arrived at "menu group," which is better than "product tags." But "menu group" is redundant and tautological.  

References to feedback from @anaulin: 
- https://discord.com/channels/704552329898360902/1243378539248619701/1243393568677298186
- https://discord.com/channels/704552329898360902/1243378539248619701/1243395493275635806

**Comment by rosschapman** [comment]
🤝 I'm going to close this ticket and wrap a bow on this prototype.
