### ISSUE TITLE
🌱🥔⛰️🔌 `Utilities`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#252]
Utilities are how Convene Neighborhoods, Spaces, and Furniture integrate with other services on the web.  Some examples:

- The Stripe Utility allows a Space or Furniture to receive online payments. 
- The Plaid Utility allows 
- The Jitsi Utility provides real-time Video and Audio support.
- The AirTable Utility allows Furniture to reflect data from a shared Spreadsheet.
- The Google Groups Utility allows Furniture to manage Google Group Memberships programmatically.

Etc.

Utilities tend to emerge from Furniture that would like to leverage a 3rd-party service, and get extracted into the `app/utilities` folder once a few pieces of Furniture are talking to the same service.

## Use Cases
- [ ] https://github.com/zinc-collective/convene/issues/1430
- [x] https://github.com/zinc-collective/convene/issues/1002
- [x] Managing Utilities
  - [x]  🥔 Adding a Utility to a Space
  - [x] 🥔 Utilities can validate themselves
  - [x] 🥔 Utilities may be configured
  - [ ] Removing a Utility
    - [ ] In-use Utilties may not be removed
  - [ ] https://github.com/zinc-collective/convene/issues/891

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
