### ISSUE TITLE
Furniture: Event Schedula

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#38]
### This Issue May Be Closed When...

- [ ] The feature definition is placed in the codebase and...
  - [ ] Step definitions are wired in
  - [ ] Each scenario runs green when CI runs
- [ ] The booking rooms feature has been turned on for 100% of users
- [ ] There is a guide explaining how to book rooms on the Convene website
- [ ] There is an announcement written up for the Booking Rooms feature

### Feature Definition
```features/booking-rooms.feature
Scenario: Member schedules an event in an unavailable room
Scenario: Member schedules an open event in an available room
Scenario: Member schedules an internal event in an available room
Scenario: Member schedules a locked event in an available room
Scenario: Member schedules a listed event in an available room
Scenario: Member schedules an unlisted event in an available room
Scenario: Member sees all listed events
Scenario: Guest sees details for listed events that are open or locked
```

### Product Considerations

We want this to be as light as possible from a "buildout" perspective, ideally to the point where we don't even _need_ a Convene UI for most of these features. 

For example, for room availability to be discernable in non-Convene spaces,  we may want to allow users to add a Room's (or Space?)'s events as a calendar in other calendaring apps. We may want rooms to be bookable by adding a room email address to an existing calendar invite.

That said, we may want to build affordances into the Convene UI for these actions as well.

### Engineering Considerations

For booking via email, we could give every room their own calendar and their own $(space)-($room) email address (i.e. zinc-convene@convene.zinc.coop)  and use [ActionMailbox](https://edgeguides.rubyonrails.org/action_mailbox_basics.html) to process inbound emails attachments for ics files and respond as appropriate. See the [icalendar gem](https://github.com/icalendar/icalendar) for details.

For exposing a `Space` or `Room`'s events, we could look into the [Internet Calendar](https://en.wikipedia.org/wiki/ICalendar) format and the [h-event](http://microformats.org/wiki/hcalendar) format.

**Comment by zspencer** [comment]
I'm moving scheduling out of 1.0; I think it makes sense as it's own release (maybe 1.1?) but I really want us to get 1.0 out the door with baseline functionality before starting on the broader feature set.

Thoughts @colombene / @maximegalon5 / @user512?

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
