### ISSUE TITLE
Discovering Rooms

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#39]
## This Issue May Be Closed When

- [x] Workspace Members may discover listed rooms
- [x] Workspace Members cannot discover unlisted rooms
- [x] The feature definition is in the repository
- [x] The step definitions are wired in
- [x] ~There is a tutorial for entering rooms somewhere under `https://www.zinc.coop/convene/`~ We can do this later.

## Feature Definition
```features/discovering-rooms.feature
Feature: In order to interact with other people in a Workspace
         I want to be able to explore the Workspace's rooms  

Scenario: Workspace Member may discover Listed Room
  Given a Workspace with a Listed Room
  When a Workspace Member is on the Workspace Dashboard
  Then they see the Room

Scenario: Workspace Member may not discover Unlisted Room
  Given a Workspace with an Unlisted Room
  When a Workspace Member is on the Workspace Dashboard
  Then they do not see the Room

Scenario: Guest may discover Listed Room
  Given a Workspace with a Listed Room
  When a Guest is on the Workspace Dashboard
  Then they see the Room

Scenario: Guest may not discover Unlisted Room
  Given a Workspace with an Unlisted Room
  When a Guest is on the Workspace Dashboard
  Then they do not see the Room
```

## UI Mockup
![Convene - Discovering Rooms - UI Sketch](https://user-images.githubusercontent.com/50284/88491447-b391c280-cf57-11ea-88b3-0d0f2f8112c9.png)

**Comment by zspencer** [comment]
I've pulled out:
- Discovering Internal Rooms to https://github.com/zinc-collective/convene/issues/41
- Discovering Unlisted Rooms to https://github.com/zinc-collective/convene/issues/72

As I believe this particular feature is reaching "useful enough" to consider moving it into the "how do we present this to the world as part of our marketing and education efforts" stage of development.

@melissamcewen - Would you be interested in taking point on that? I don't think we want to tie in too much visuals since I expect the UI will evolve over the next few months; but the concept of "you can navigate between rooms to gather in a self-determining manner" may be worth highlighting on a sub-page or something? What do you think?

**Comment by zspencer** [comment]
Now that we have tests in place, and notes in the CHANGELOG I am going to say this is good to go.
