### ISSUE TITLE
Locked Rooms

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#40]
### Done
 - [x] Locking a Room
    - [x] [Wireframe](https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/847810bf-5d62-4131-a70d-d9efdfadb334)
    - [x] Define [Scenario](https://github.com/zinc-collective/convene/blob/70b65c82148c20db0c2b580715b0825325ccfbe6/features/locking-rooms.feature#L41-L44)
    - [x] Wire in Steps
    - [x] Implement Feature
  
 - [x] Unlocking a Room
    - [x] [Wireframe](https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/847810bf-5d62-4131-a70d-d9efdfadb334)
    - [x] Define [Scenario](https://github.com/zinc-collective/convene/blob/70b65c82148c20db0c2b580715b0825325ccfbe6/features/locking-rooms.feature#L61-L64)
    - [x] Wire in Steps
    - [x] Implement Feature
 - [x] Failing to enter a locked room
   - [x] Define [Scenario](https://github.com/zinc-collective/convene/blob/70b65c82148c20db0c2b580715b0825325ccfbe6/features/locking-rooms.feature#L28)
   - [x] Wire in Steps
   - [x] Implement Feature
- [x] [Demo workspace has a Locked Room with the password “friend”](https://github.com/zinc-collective/convene/commit/a36e2c2d9e0a7f5e05df127af3e9dfec9e94cf56)
 - [x] Access Code input becomes editable only when room is locked (per @colombene, see: https://github.com/zinc-collective/convene/pull/139#issuecomment-709625969) (https://github.com/zinc-collective/convene/pull/144)
- [x] Document the features intent within [`/features/locking-rooms.feature`](https://github.com/zinc-collective/convene/blob/development/features/locking-rooms.feature) (https://github.com/zinc-collective/convene/pull/54)
 - [x] Entering a Locked Room
    - [x] [Wireframe](https://xd.adobe.com/view/fd425dbe-5384-44c9-997a-eeee6e886a86-a811/screen/04ee266e-931b-4bde-bcf9-af94c7ac444e/)
    - [x] Define [Scenario](https://github.com/zinc-collective/convene/blob/70b65c82148c20db0c2b580715b0825325ccfbe6/features/locking-rooms.feature#L23-L28)
    - [x] Wire in Steps
    - [x] [Implement Feature](https://github.com/zinc-collective/convene/commit/ab35431b38553f04db249e1a5b383c13937f5ec4)
    - [x] Indicate which rooms are Locked in the Dashboard
 - [x] Clean up the way we determine which Room we are interacting with in our feature tests.
   - It turns out the parameter Types are really great at pulling out the specific pieces of information (access code, visiblity, room etc) but when you need a representation of the intersection of these things, it becomes a bit hairy; and you either need to override it in your step definitions; or you need to make a greedy parameter type. We are considering using a higher-order function whose job is to sit in between the step definition and function that the step definition calls. Example feature def and step definition:
   ```features/locked-rooms.feature
   Given a Locked Room
 
   ```
    ```step_defitions/room_steps.js
    Given("{accessLevel} {room}", linkParameterTypes(async function(room) {
      ...
    })
    ```
- [x] Write a Guide to Locking and Unlocking Rooms that communicates _who_, _what_, _where_, _when_, _why_ and _how_.

### Deferred

- [X] ~Secure the videobridge servers!  Note: We are unsure how to do this cleanly.~ Note: We are not including this in Andromeda. See https://github.com/zinc-collective/convene/issues/156

**Comment by zspencer** [comment]
@anaulin and I paired today; and while we think using JWT or other mechanisms to prevent access to the Jitisi videobridge in Andromeda is costing us more than it's worth given our ~12 regular users of Convene.

We are going to split out a new ticket; and put that into the next milestone; and we'll start collecting notes on how we could go about this in the new ticket.

**Comment by zspencer** [comment]
I want to say a _huge_ thank you to @colombene, @anaulin, @user512, @roseaboveit, @cjoulain, @KellyAH, and @eg-bet for all their hard work carrying this feature across the finish line. You all are _the best_!!!
