### ISSUE TITLE
Acquisition: Demoing Convene

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#61]
```features/demoing-convene.feature
Feature: Demoing Convene
  In order to determine if Convene is a product I would like to use
  I want to walk through it's value proposition for my particular context


Scenario: Prospective Client Schedules a Demo
  Given I am on the Convene landing page
  When I schedule a demo
  Then an email is sent to my email address with the demo information and a calendar invite 
  And an email is sent to convene-customer-team@zinc.coop with the demo information and a calendar invite


Scenario: Customer Team Member May Perform a Demo
  Given a fresh Convene deployment
  When I visit the fresh deployment
  Then there is a Convene-Demo Workspace
  And the Convene-Demo Workspace has a Room named "Vivek's Desk"
  And the Convene-Demo Workspace has a Room named "Zee's Desk"
  And the Convene-Demo Workspace has a Room named "Water Cooler"
  And the Convene-Demo Workspace has a Room named "The Ada Lovelace Room"
  And I can access the `convene-demo` workspace directly via `https://convene-demo.{{ deploymentDomain }}`
```

### TODO
- [x] Put the feature tests in the repo
- [x] Create a `Convene Demo` workspace
- [x] Smoke test! Ensure convene-demo.zinc.coop lands us in the `convene-demo` workspace on production
- [ ] Wire in the step definitions so the feature tests work
- [ ] Integrate the Convene Demo calendly into the Convene landing page somehow
