### ISSUE TITLE
🥔✨ `Space`: `Domain`s

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#74]
While `Space`s in a neighborhood can be accessed at their neighborhood address (i.e. https://neighborhood.example.com/spaces/space-handle); Commercial Clients expect People would visit a Space via a domain that represents their organization. 

## Use Cases
- [x] 🥔✨ Visiting a `Space` via a `Domain`
- [x] #1513
- [ ] 🌫️ Registering a `Domain`
- [ ] 🌫️ Emailing from a `Domain`

## Operator Experience
- [ ] Automate allocation of the `Space` Domain with the `Neighborhood` Infrastructure
  - [ ] DNS Provider (Cloudflare)
  - [ ] Web Host (Heroku)
  - [ ] Transactional Email Service?

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424)
