### ISSUE TITLE
Furniture: Videobridge - Granting Permissions on iPhone

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#77]
### TODO

- [ ] (Code) We can determine programmatically if we have Camera and Microphone permissions within a VideoRoom
- [ ] (Design, Code) We let attendees know that they have not granted the correct permissions
- [ ] (Doc) We have a guide written on how to allow Camera and Microphone permissions on iPhone
- [ ] (Test) We have placed the Feature test in `features/granting-permissions.feature`

### Feature Definition

```feature/granting-permissions.feature
Feature: Granting permissions
  In order to participate in conversations on Convene
  I want to allow my device to use my camera and microphone

Scenario: iPhone Attendee is shown how to allow microphone and camera
  Given I am using an iPhone that has been configured not to allow microphone or camera access in Safari
  When I enter a Room
  Then a Video conversation is not started
  And I am prompted with how to allow my camera and microphone to be used

Scenario: iPhone Attendee grants microphone and camera permissions
  Given I have entered a Room using an iPhone that has been configured not to allow microphone or camera access in Safari
  When I grant permissions for microphone and camera
  Then the Video conversation is started
```
