### ISSUE TITLE
🌱🌫️⛰️✨ `Groups`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#811]
- https://github.com/zinc-collective/convene/issues/117 have broad permissions within https://github.com/zinc-collective/convene/issues/1154. `Groups` narrow those permissions down.

## Use Cases

- [ ] `Group` may have non-Member-level access to a `Space`
- [ ] `Group` may have non-Member-level access to a `Section`
- [ ] `Group` may have Member-level access to a `Section`
