### ISSUE TITLE
Furniture: Videobridge - "Opening" a Space

### ISSUE THREAD

**Issue by user512** [zinc-collective/convene#9]
```features/on-demand-video-room.feature
Feature: On-demand video rooms
  In order to have to have better control over my budget
  as Felicia or Colin
  I want video room costs only accrue when an event is scheduled.

Scenario: Felicia starts an on-demand Video Room via Calendar Invite
  Given a Felicia has an active membership to Convene and a Named Video Room
  When Felicia invites their Named Video Room to a Calendar Invite via Email
  Then a Video Room is launched 15 minutes before the event start time
  And the Video Room is terminated 15 minutes after the events end time
```

## This Issue May Be Closed When

- [ ] We have written a guide to using on-demand video rooms via calendaR
- [ ] A team member who was not involved in designing or developing the feature has confirmed it works
- [ ] We have announced the new feature to the convene feature release communication channel(s).

**Comment by zspencer** [comment]
I'd like to propose the following scenario as the first step on this epic journey:
```
Scenario: Client starts an on-demand video room via an API Call
  Given a Client with API Access
  When the Client uses the API to start an on-demand video room with:
  | option | value |
  | launch_at | now |
  | duration | 60 |
  Then a Video Room is launched immediately for that Client
  And that Video Room is terminated after 60 minutes
```

By making it API driven before we get to the user interface, we can build our network of contributors and client's simultaneously. It also puts us in a place where we can leverage the core technology of on-demand, reasonably high-quality streaming audio or video in other product(s) and service(s).

Thoughts fellow @zinc-collective/convene-maintainers?

**Comment by zspencer** [comment]
I've went ahead and decided to center this on [Felicia the Facilitator](https://docs.google.com/document/d/1JwTh2uFTc6pxsXu3njEVKQrv-J5HWExhd1rgT-ravt4/edit#heading=h.vr0savi1xczp) (a persona that @maximegalon5 came up with) and made the call to use calendar invites. It may be the wrong call, but at least it gets us a little bit closer. We can always spin out a new issue for the feature where it's done via API.

I think this makes the feature "doable" now, without need for further shaping. The next question becomes "what milestone do we want this in?" is this an alpha-0.1 feature or is it something that can wait a few months?

**Comment by maximegalon5** [comment]
To clarify the flow is the idea here that a _Convene_ link is pasted onto a calendar invite in the _Location_ section? And then _Convene_ knows to get the server up and running before the meeting time, and keep it running till it is manually stopped or will the server wind down automatically after the allotted time (15 mins after the meeting ends) if not in use?

**Comment by zspencer** [comment]
At present, I think that's a bit too hard; I was thinking we'd create en email address per-client which they can invite to an event. I.e.  "We've invited `convene-scheduler+zinc@zinc.coop` from 10AM to 4PM every Friday." will make sure that the `meet.zinc.coop` infrastructure is up and running for that time window.

In the future, we could also use this to scale sizing on-demand: "Oh you invited 20 people to this event, but you're on the $.12c/hr size which supports 10 people... Would you like to use the $.25c/hr size?"
