### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#91]
## This Issue May Be Closed When
- [X] When screen sharing, the video portal fills the entire display
- [X] ~When screen sharing ends, the video panel shrinks~
- [ ] The feature definition is added to source control
- [ ] The feature definition’s steps are wired in 
- [ ] The Release Notes include the screen sharing feature
- [ ] There is a written guide to using screen sharing

## Feature Definition
```features/screen-sharing.feature
Feature: Screen Sharing
  In order to show what we’re working on
  I want to be able to share my screen with a Room

  Scenario: Beginning Screen Sharing
    Given I am in in a Video Room
    When Screen Sharing begins
    Then I can see the shared screen 
    And the Video fills entire screen width and height
    And I can scroll past the Video to get to the other Room elements
```

## Implementation Details

The Jitsi iFrame API _does_ have a `screenSharingStatusChanged` event<sup>[0]</sup>, which we can use to set the `width` and `height` attributes on the iFrame to `100vh` and `100vw`<sup>[1]</sup> respectively; thus ensuring that screen fills the entire browser screen.

We should be able to listen to this event in [video_room.js](https://github.com/zinc-collective/convene/blob/development/convene-web/app/javascript/src/video_room.js) and swap classes on the containing element. Perhaps adding a class like `screen-sharing--active` to the iFrame itself?

[0]: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
[1]: https://stackoverflow.com/questions/25225682/difference-between-width100-and-width100vw
