### ISSUE TITLE
🌫️🗜️✨ `Gizmo`: `Long-Term Roadmap`

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/convene#989]
Come Together, Set Your Trajectory, and Progress Towards Long Term Shared Goals

#### Guide - _  Indicates Timeline and Direction of the Roadmap_

_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

### Client Owners:
- https://github.com/zinc-collective/convene/issues/988

### Use Cases
- [ ] Setting Trajectory
  - [ ] Guide may place Milestone (title, description, date to start thinking about it, date it wants to be done by)
  - [ ] Guide may add Tasks to Milestone (title, description)
  - [ ] Guide may update Milestones
  - [ ] Guide may update Tasks
- [ ] Progress Towards Long Term Shared Goals
  - [ ] Collaborator may attach Files to Milestone
  - [ ] Collaborator may attach Files to Tasks
  - [ ] Collaborator may Complete Tasks on Milestone
  - [ ] Collaborator may Comment on Tasks
  - [ ] Collaborator may Comment on Milestones
  
_Wish this was further along? Consider sponsoring our [Zinc Community Fund](https://opencollective.com/zinc-community), which we use to cover our operating costs and pay contributors!_

**Comment by rosschapman** [comment]
🧹  Relegated to [cold storage](https://docs.google.com/spreadsheets/d/1Z_pC21sAKAMyB7xiRAY1--bm1ZKEuFzCzSXfqzHaF08/edit?gid=1828229424#gid=1828229424).
